[package]
name = "synchronicity"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
abscissa_core = "0.4.0"
failure = "0.1"
gumdrop = "0.7"
lazy_static = "1"
serde = { version = "1", features = ["serde_derive"] }

[dev-dependencies.abscissa_core]
version = "0.4.0"
features = ["testing"]

